name:                servant-streaming-server
version:             0.3.0.0
synopsis:            Server instances for the 'servant-streaming' package.
description:         >
    This package defines instances that allow using the 'StreamBody' and
    'StreamResponse' combinators in 'servant' servers.
homepage:            http://github.com/plow-technologies/servant-streaming-server#readme
license:             BSD3
license-file:        LICENSE
author:              Julian K. Arni
maintainer:          jkarni@gmail.com
copyright:           (c) Julian K. Arni
github:              plow-technologies/servant-streaming-server
tested-with:         GHC == 8.2.2

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 4.13
  - bytestring
  - resourcet >= 1.1 && < 1.3
  - servant
  - servant-server >= 0.13 && < 0.16
  - servant-streaming >= 0.2 && < 0.4
  - streaming >= 0.1 && < 0.3
  - streaming-wai >= 0.1 && < 0.2
  - wai >= 3.0 && < 3.3
  - http-media >= 0.6 && < 0.8
  - http-types >= 0.9 && < 0.13

default-extensions:
  - AutoDeriveTypeable
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - KindSignatures
  - MultiParamTypeClasses
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators

library:
  source-dirs:      src
  other-modules:    []

tests:
  spec:
    main:            Spec.hs
    source-dirs:     test
    ghc-options:     -Wall -with-rtsopts=-T -threaded
    dependencies:
      - servant-streaming-server
      - hspec > 2 && < 3
      - QuickCheck >= 2.8 && < 2.13
      - pipes >= 4 && < 5
      - pipes-http >= 1 && < 2
      - streaming-bytestring >= 0.1 && < 0.2
      - warp >= 3.2.4 && < 3.3
      - directory
